### ISSUE TITLE
RF Ablation Planner

### ISSUE THREAD

**Issue by AliceSantilli** [SlicerRt/SlicerRT#107]
**Workflow Plan - Phase 1 **

- [x] Segmentation 
    - [x] Import segmentation of organ and lesions 
- [x]  3D Visualization of lesions, organs and margins
    - [x] add a margin to the lesion 
- [x] Set parameters for ablation 
    - [x] Burn Time 
    - [x] Input volume 
    - [x] Markups list to be set as needle tip location 

OR 
- [ ] Import Multi needle plan to set the parameters 

- [x] Calculate Dose Volume 

    - [x] forward planning system 
    - [x] combined impact of nearby ablation points accounted for 
    - [x] Pennes BioHeat Equation 
- [x] Display Isodose volume 
    - [x] Isodose module 
- [ ] Select needle entry point 
    - [x] Select from list of points belonging to the selected markups node
    - [x] with ability to reset needles 
    - [ ] manipulate fiducial and have needle rotate and transform with it 
- [x] Provide User with plan feedback 
    - [x] Create a dose volume histogram of the segments and display

**Comment by AliceSantilli** [comment]
** Phase 1 (B) ** 

- [ ] Incorporate a more sophisticated calculation 
    - [ ] On that involves subtracting from voxels surrounding major blood vessels of a threshold diameter. 
    - [ ] Get images in which we can segment out blood vessels

**Comment by cpinter** [comment]
Closing. Extension can be found here:

https://github.com/PerkLab/AblationPlanner
